# Generated by Django 6.0.3 on 2026-05-09 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_focussession_studygroup_studygroupmembership_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplan',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='difficulty',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='exam_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='weaktopic',
            name='understanding_level',
            field=models.CharField(choices=[('weak', 'Weak'), ('medium', 'Medium'), ('strong', 'Strong')], db_index=True, default='weak', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'scheduled_for'], name='planner_not_user_id_089502_idx'),
        ),
        migrations.AddIndex(
            model_name='progresslog',
            index=models.Index(fields=['user', '-logged_at'], name='planner_pro_user_id_41cc1e_idx'),
        ),
        migrations.AddIndex(
            model_name='progresslog',
            index=models.Index(fields=['subject', 'completed'], name='planner_pro_subject_2491cb_idx'),
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['user', '-created_at'], name='planner_stu_user_id_1154e1_idx'),
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['user', 'end_date'], name='planner_stu_user_id_20f3f4_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'date'], name='planner_stu_user_id_806828_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['plan', 'date', 'start_time'], name='planner_stu_plan_id_8fecd0_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['subject', 'is_completed'], name='planner_stu_subject_05a883_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['user', 'exam_date'], name='planner_sub_user_id_074f64_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['user', 'priority'], name='planner_sub_user_id_c84b6f_idx'),
        ),
        migrations.AddIndex(
            model_name='weaktopic',
            index=models.Index(fields=['user', 'is_completed'], name='planner_wea_user_id_1436a2_idx'),
        ),
        migrations.AddIndex(
            model_name='weaktopic',
            index=models.Index(fields=['subject', 'is_completed'], name='planner_wea_subject_63d5a8_idx'),
        ),
    ]
