# Generated by Django 6.0.4 on 2026-05-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_studyplan_end_date_alter_studysession_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='target_score',
            field=models.PositiveSmallIntegerField(default=90),
        ),
    ]
