# Generated by Django 6.0.3 on 2026-05-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_subject_target_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'MCQ'), ('true_false', 'True/False'), ('short', 'Short Answer'), ('fill_blank', 'Fill in the Blanks'), ('rapid', 'Rapid Revision')], default='mcq', max_length=20),
        ),
    ]
