# Generated by Django 6.0.3 on 2026-05-16 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_alter_quizquestion_question_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('recommendation', models.TextField()),
                ('study_focus', models.CharField(max_length=180)),
                ('revision_focus', models.CharField(blank=True, max_length=180)),
                ('estimated_minutes', models.PositiveIntegerField(default=60)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('confidence', models.PositiveSmallIntegerField(default=70)),
                ('study_order', models.JSONField(blank=True, default=list)),
                ('source_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-source_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'source_date'], name='planner_air_user_id_21ae7a_idx'), models.Index(fields=['user', 'priority'], name='planner_air_user_id_6a6fd0_idx')],
            },
        ),
        migrations.CreateModel(
            name='BurnoutSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.PositiveSmallIntegerField(default=0)),
                ('wellness_score', models.PositiveSmallIntegerField(default=100)),
                ('stress_indicators', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='planner_bur_user_id_4153e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('question_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('score_percent', models.PositiveSmallIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('weak_topics', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weak_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.weaktopic')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='planner_qui_user_id_e73025_idx'), models.Index(fields=['subject', 'difficulty'], name='planner_qui_subject_11dddc_idx')],
            },
        ),
    ]
