# Generated by Django 6.0.3 on 2026-05-16 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_airecommendation_burnoutsnapshot_quizattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Mentor conversation', max_length=160)),
                ('mode', models.CharField(choices=[('exam', 'Exam Mentor'), ('revision', 'Revision Mentor'), ('coding', 'Coding Mentor'), ('productivity', 'Productivity Coach'), ('quick', 'Quick Doubt Solver')], default='exam', max_length=24)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('mode', models.CharField(default='exam', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='planner.mentorconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('action', models.TextField()),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('detail', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success')], default='info', max_length=20)),
                ('source', models.CharField(default='mentor', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLearningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_style', models.CharField(default='structured active recall', max_length=80)),
                ('preferred_study_time', models.CharField(blank=True, max_length=80)),
                ('favorite_subjects', models.JSONField(blank=True, default=list)),
                ('long_term_goals', models.TextField(blank=True)),
                ('response_depth', models.CharField(default='balanced', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('value', models.TextField()),
                ('confidence', models.PositiveSmallIntegerField(default=70)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('user', 'key')},
            },
        ),
        migrations.AddIndex(
            model_name='mentorconversation',
            index=models.Index(fields=['user', '-updated_at'], name='planner_men_user_id_a1489d_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorconversation',
            index=models.Index(fields=['user', 'is_pinned'], name='planner_men_user_id_ce4cc9_idx'),
        ),
        migrations.AddIndex(
            model_name='mentormessage',
            index=models.Index(fields=['conversation', 'created_at'], name='planner_men_convers_d822fe_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorrecommendation',
            index=models.Index(fields=['user', 'priority'], name='planner_men_user_id_539f86_idx'),
        ),
        migrations.AddIndex(
            model_name='studyinsight',
            index=models.Index(fields=['user', '-created_at'], name='planner_stu_user_id_2c7bf8_idx'),
        ),
    ]
